// rsventajaweb/src/app/pages/controlpanel/controlpanel.component.ts
import { Component, OnInit } from '@angular/core';
import { SecurityService } from 'src/app/services/security.service';
import { BehaviorSubject, Observable, of, Subject } from 'rxjs';
import { PolicyService } from 'src/app/services/policy.service';
import { Policy } from 'src/app/model/policy.model';
import { FormGroup, FormBuilder } from '@angular/forms';
import { Insurer } from 'src/app/model/insurer.model';
import { InsurerService } from 'src/app/services/insurer.service';
import { NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import { faCalendar } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-controlpanel',
  templateUrl: './controlpanel.component.html',
  styleUrls: ['./controlpanel.component.css']
})
export class ControlpanelComponent implements OnInit {
  displayedColumns: string[] = ['renewal', 'days', 'name', 'insurer', 'additional', 'start', 'end', 'download'];
  displayedColumnsCurrent: string[] = ['days', 'name', 'insurer', 'additional', 'start', 'end', 'download'];  
  displayedColumnsAll: string[] = ['name', 'insurer', 'additional', 'start', 'end', 'download', 'delete'];
  signedin: boolean = false;
  policies$: Observable<Policy[]>;
  queryCurrentPolicies$: Observable<Policy[]>;
  queryCurrentForm: FormGroup;
  queryPoliciesSubject$: BehaviorSubject<Policy[]> = new BehaviorSubject<Policy[]>([]);
  queryPolicies$: Observable<Policy[]>;
  queryPolicies: Policy[];
  insurers$: Observable<Insurer[]>;
  queryForm: FormGroup;
  insertForm: FormGroup;
  model: NgbDateStruct;
  file: string | ArrayBuffer;
  fileName: string;
  accept: "application/pdf";
  faCalendar = faCalendar;
  addingPolicy = false;
  displayAlert = false;
  displaySuccess = false;
  danger: 'Alertando aos usuarios';
  displayQueryCurrent = false;
  displayQueryAll = false;
  constructor(private securityService: SecurityService, private formBuilder: FormBuilder,
    private policyService: PolicyService, private insurerService: InsurerService) {
    this.queryCurrentForm = this.formBuilder.group({
      query: ''
    });
    this.queryForm = this.formBuilder.group({
      query: ''
    });
    this.insertForm = this.formBuilder.group({
      name: '',
      insurer: 0,
      additionalInfo: '',
      startDate: null,
      endDate: null,
      file: ''
    });
  }

  async ngOnInit() {
    this.signedin = this.securityService.verifyAuthentication(sessionStorage.getItem("Token"));
    this.loadData();
  }

  loadData() {
    this.policies$ = this.policyService.getDuePolicies();
    this.insurers$ = this.insurerService.getInsurers();
  }

  calculateDays(endDate: Date): number {
    let nowDate = new Date();
    endDate = new Date(endDate);
    return Math.floor((endDate.getTime() - nowDate.getTime()) / 1000 / 60 / 60 / 24);
  }

  fileUrl(fileName: string) {
    return (`https://policiesrsventaja.s3-sa-east-1.amazonaws.com/${fileName}`)
  }

  onCurrentPoliciesSubmit(queryCurrentForm: FormGroup) {
    if (queryCurrentForm.value.query.length > 0) {
      this.displayQueryCurrent = false;
      this.queryCurrentPolicies$ = this.policyService.getPoliciesQuery(queryCurrentForm.value.query, true);
      this.queryCurrentForm.reset();
    } else {
      this.displayQueryCurrent = true;
    }
  }

  onPoliciesSubmit(queryForm: FormGroup) {
    this.queryPolicies$ = this.queryPoliciesSubject$.asObservable();
    if (queryForm.value.query.length > 0) {
      this.displayQueryAll = false;
      this.policyService.getPoliciesQuery(queryForm.value.query, false).subscribe(policies => {
        this.queryPolicies = policies;
        this.queryPoliciesSubject$.next(policies);
        });
      this.queryForm.reset();
    } else {
      this.displayQueryAll = true;
    }
  }

  async updateRenewalStarted(id: number, evt) {
    let bool = !evt;
    await this.policyService.updateRenewalStarted(id, bool).toPromise();;
  }

  async onInsertSubmit(insertForm: FormGroup) {
    this.addingPolicy= true;
    const form = insertForm.value;
    if (form.additionalInfo.length > 0 && form.name.length > 0 && form.insurer > 0 && form.startDate && form.endDate && form.additionalInfo.length > 0) {
      this.displayAlert = false;
      await this.policyService.addPolicy(form.name.toUpperCase(), form.additionalInfo.toUpperCase(), form.startDate, form.endDate, form.insurer, this.file as string, this.fileName).toPromise();
      insertForm.reset();      
      this.displaySuccess = true;
    } else {
      this.displayAlert = true;
    }
    this.addingPolicy = false;
  }

  handleUpload() {
    const file = this.insertForm.value.file;
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      this.file = (reader.result as string).split(';base64,')[1];
      this.fileName = file.name;
    };
  }

  delete(id: number, fileName: string) {
    this.policyService.deletePolicy(id, fileName).subscribe(_ =>
      {
        var index = this.queryPolicies.map(x => {
          return x.id;
        }).indexOf(id);  

        this.queryPolicies.splice(index, 1);
        this.queryPoliciesSubject$.next(this.queryPolicies.slice(0));
      }
      );  
  }

  close() {
    this.displayAlert = false;
    this.displaySuccess = false;
  }

  closeQueryCurrent() {
    this.displayQueryCurrent = false;
  }

  closeQueryAll() {
    this.displayQueryAll = false;
  }
}

<nav class="navbar navbar-expand-lg">
  <div fxLayout="row" fxLayoutAlign="space-between center" fxLayoutGap="20px" class="navbar-collapse">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="">Página Inicial</a>
          </li>
        </ul>
  </div>
</nav>
<div class="jumbotron text-center">
  <img alt="RS Ventaja" src="../assets/rsventajaheader.png" width="200" height="200">
</div>
<ng-container *ngIf="signedin">
  <mat-tab-group>
    <mat-tab label="Apólices a vencer">
      <div *ngIf="policies$ | async as pols" class="content container-fluid">
        <div class="title">Apólices com vencimento nos próximos 30 dias</div>
        <table mat-table [dataSource]="pols" class="mat-elevation-z2">
          <ng-container matColumnDef="renewal">
            <th mat-header-cell *matHeaderCellDef>Calculado?</th>
            <td mat-cell *matCellDef="let element">
              <mat-checkbox #checkbox color="primary" [checked]="element.calculated"
                (click)="updateRenewalStarted(element.id, checkbox.checked)">
              </mat-checkbox>
            </td>
          </ng-container>
          <ng-container matColumnDef="days">
            <th mat-header-cell *matHeaderCellDef>Dias Restantes</th>
            <td mat-cell *matCellDef="let element"> {{ calculateDays(element.end_date) }} </td>
          </ng-container>
          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef>Nome</th>
            <td mat-cell *matCellDef="let element">
              {{ element.name }}
            </td>
          </ng-container>
          <ng-container matColumnDef="insurer">
            <th mat-header-cell *matHeaderCellDef>Seguradora</th>
            <td mat-cell *matCellDef="let element">
              {{ element.insurer }}
            </td>
          </ng-container>
          <ng-container matColumnDef="additional">
            <th mat-header-cell *matHeaderCellDef>Informações Adicionais</th>
            <td mat-cell *matCellDef="let element">
              {{ element.detail }}
            </td>
          </ng-container>
          <ng-container matColumnDef="start">
            <th mat-header-cell *matHeaderCellDef>Início</th>
            <td mat-cell *matCellDef="let element">
              {{ element.start_date | date:'shortDate':'':'pt-BR' }}
            </td>
          </ng-container>
          <ng-container matColumnDef="end">
            <th mat-header-cell *matHeaderCellDef>Vencimento</th>
            <td mat-cell *matCellDef="let element">
              {{ element.end_date | date:'shortDate':'':'pt-BR' }}
            </td>
          </ng-container>
          <ng-container matColumnDef="download">
            <th mat-header-cell *matHeaderCellDef>Ação</th>
            <td mat-cell *matCellDef="let element">
              <a mat-flat-button color="primary" href="{{fileUrl(element.file_name)}}" target="_blank">Abrir</a>
            </td>
          </ng-container>
          <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
        </table>
      </div>
    </mat-tab>
    <mat-tab label="Buscar apólices vigentes">
      <div class="content container-fluid contain">
        <ngb-alert *ngIf="displayQueryCurrent" (close)="closeQueryCurrent()">Favor preencher o nome para realizar a
          busca.</ngb-alert>
        <div class="title">Buscar apólices vigentes</div>
        <form [formGroup]="queryCurrentForm" (ngSubmit)="onCurrentPoliciesSubmit(queryCurrentForm)">
          <div fxLayout="column" fxLayoutAlign="start start">
            <mat-form-field style="width:400px !important" appearance="fill">
              <mat-label>Digite parte ou o nome do cliente</mat-label>
              <input matInput type="text" formControlName="query">
            </mat-form-field>
            <div style="padding-left: 0.5em">
              <button mat-raised-button color="primary" type="submit">Buscar</button>
            </div>
          </div>
        </form><br><br>
        <table *ngIf="queryCurrentPolicies$ | async as cpols" mat-table [dataSource]="cpols" class="mat-elevation-z2">
          <ng-container matColumnDef="days">
            <th mat-header-cell *matHeaderCellDef>Dias Restantes</th>
            <td mat-cell *matCellDef="let element"> {{ calculateDays(element.end_date) }} </td>
          </ng-container>
          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef>Nome</th>
            <td mat-cell *matCellDef="let element">
              {{ element.name }}
            </td>
          </ng-container>
          <ng-container matColumnDef="insurer">
            <th mat-header-cell *matHeaderCellDef>Seguradora</th>
            <td mat-cell *matCellDef="let element">
              {{ element.insurer }}
            </td>
          </ng-container>
          <ng-container matColumnDef="additional">
            <th mat-header-cell *matHeaderCellDef>Informações Adicionais</th>
            <td mat-cell *matCellDef="let element">
              {{ element.detail }}
            </td>
          </ng-container>
          <ng-container matColumnDef="start">
            <th mat-header-cell *matHeaderCellDef>Início</th>
            <td mat-cell *matCellDef="let element">
              {{ element.start_date | date:'shortDate':'':'pt-BR' }}
            </td>
          </ng-container>
          <ng-container matColumnDef="end">
            <th mat-header-cell *matHeaderCellDef>Vencimento</th>
            <td mat-cell *matCellDef="let element">
              {{ element.end_date | date:'shortDate':'':'pt-BR' }}
            </td>
          </ng-container>
          <ng-container matColumnDef="download">
            <th mat-header-cell *matHeaderCellDef>Ação</th>
            <td mat-cell *matCellDef="let element">
              <a mat-flat-button color="primary" href="{{fileUrl(element.file_name)}}" target="_blank">Abrir</a>
            </td>
          </ng-container>
          <tr mat-header-row *matHeaderRowDef="displayedColumnsCurrent"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumnsCurrent;"></tr>
        </table>
      </div>
    </mat-tab>
    <mat-tab label="Buscar apólices">
      <div class="content container-fluid contain">
        <ngb-alert *ngIf="displayQueryAll" (close)="closeQueryAll()">Favor preencher o nome para realizar a busca.
        </ngb-alert>
        <div class="title">Buscar apólices</div>
        <form [formGroup]="queryForm" style="text-align: center" (ngSubmit)="onPoliciesSubmit(queryForm)">
          <div fxLayout="column" fxLayoutAlign="start start">
            <mat-form-field style="width:400px !important" fxFlex appearance="fill">
              <mat-label>Digite parte ou o nome do cliente</mat-label>
              <input matInput type="text" formControlName="query">
            </mat-form-field>
            <div style="padding-left: 0.5em;">
              <button mat-raised-button color="primary" type="submit">Buscar</button>
            </div>
          </div>
        </form><br><br>
        <table *ngIf="queryPolicies$ | async as apols" mat-table [dataSource]="apols" class="mat-elevation-z2">
          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef>Nome</th>
            <td mat-cell *matCellDef="let element">
              {{ element.name }}
            </td>
          </ng-container>
          <ng-container matColumnDef="insurer">
            <th mat-header-cell *matHeaderCellDef>Seguradora</th>
            <td mat-cell *matCellDef="let element">
              {{ element.insurer }}
            </td>
          </ng-container>
          <ng-container matColumnDef="additional">
            <th mat-header-cell *matHeaderCellDef>Informações Adicionais</th>
            <td mat-cell *matCellDef="let element">
              {{ element.detail }}
            </td>
          </ng-container>
          <ng-container matColumnDef="start">
            <th mat-header-cell *matHeaderCellDef>Início</th>
            <td mat-cell *matCellDef="let element">
              {{ element.start_date | date:'shortDate':'':'pt-BR' }}
            </td>
          </ng-container>
          <ng-container matColumnDef="end">
            <th mat-header-cell *matHeaderCellDef>Vencimento</th>
            <td mat-cell *matCellDef="let element">
              {{ element.end_date | date:'shortDate':'':'pt-BR' }}
            </td>
          </ng-container>
          <ng-container matColumnDef="download">
            <th mat-header-cell *matHeaderCellDef>Abrir</th>
            <td mat-cell *matCellDef="let element">
              <a mat-flat-button color="primary" href="{{fileUrl(element.file_name)}}" target="_blank">Abrir</a>
            </td>
          </ng-container>
          <ng-container matColumnDef="delete">
            <th mat-header-cell *matHeaderCellDef>Excluir</th>
            <td mat-cell *matCellDef="let element">
              <a mat-flat-button color="accent" (click)="delete(element.id, element.file_name)" target="_blank">Excluir</a>
            </td>
          </ng-container>
          <tr mat-header-row *matHeaderRowDef="displayedColumnsAll"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumnsAll;"></tr>
        </table>
      </div>
    </mat-tab>
    <mat-tab label="Cadastrar apólice">
      <div class="content2 container-fluid contain mat-elevation-z2">
        <ngb-alert *ngIf="displayAlert" (close)="close()">Favor preencher todos os campos antes de prosseguir!
        </ngb-alert>
        <ngb-alert type="success" *ngIf="displaySuccess" (close)="close()">Cadastro realizado com sucesso!
        </ngb-alert>
        <div class="title">Cadastrar apólice</div>
        <div class="center">
          <mat-progress-spinner *ngIf="addingPolicy" style="margin:0 auto;" class="example-margin" color="primary"
            mode="indeterminate">
          </mat-progress-spinner>
        </div>
        <form [formGroup]="insertForm" (ngSubmit)="onInsertSubmit(insertForm)">
          <div fxLayout="column">
            <mat-form-field class="full-width" appearance="fill">
              <mat-label>Nome do proponente</mat-label>
              <input matInput type="text" formControlName="name">
            </mat-form-field>
            <mat-form-field class="full-width" appearance="fill">
              <mat-label>Seguradora</mat-label>
              <mat-select formControlName="insurer">
                <mat-option *ngFor="let insurer of insurers$ | async" [value]="insurer.id">{{ insurer.name }}
                </mat-option>
              </mat-select>
            </mat-form-field>
            <mat-form-field class="full-width" appearance="fill">
              <mat-label>Informações adicionais</mat-label>
              <input matInput type="text" maxlength="50" formControlName="additionalInfo">
            </mat-form-field>
            <mat-form-field appearance="fill">
              <mat-label>Data de <b>início</b> de vigência</mat-label>
              <input matInput [matDatepicker]="picker" formControlName="startDate">
              <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
              <mat-datepicker #picker></mat-datepicker>
            </mat-form-field>
            <mat-form-field appearance="fill">
              <mat-label>Data de <b>fim</b> de vigência</mat-label>
              <input matInput [matDatepicker]="picker2" formControlName="endDate">
              <mat-datepicker-toggle matSuffix [for]="picker2"></mat-datepicker-toggle>
              <mat-datepicker #picker2></mat-datepicker>
            </mat-form-field>
            <div fxLayout="row" fxLayoutAlign="space-evenly center">
              <mat-form-field class="full-width" appearance="fill">
                <ngx-mat-file-input valuePlaceholder="danger" accept=".pdf" formControlName="file"
                  (change)="handleUpload()">
                </ngx-mat-file-input>
              </mat-form-field>
            </div>
            <button class="full-width" mat-raised-button color="primary" type="submit">Cadastrar</button>
          </div>
        </form>
      </div>
    </mat-tab>
  </mat-tab-group>
</ng-container>

// rsventajaweb-react/src/ControlPanel.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Tabs, Tab, Table, Button, Form, Alert, Spinner } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';

// Mock data and functions
const mockPolicies = [
  { id: 1, customer_name: 'João Silva', detail: 'Seguro Auto', start_date: '2024-06-01', end_date: '2024-07-01', calculated: false, insurer: 'Porto Seguro', file_name: 'mock.pdf' },
  { id: 2, customer_name: 'Maria Souza', detail: 'Seguro Vida', start_date: '2024-05-15', end_date: '2024-06-20', calculated: true, insurer: 'SulAmérica', file_name: 'mock2.pdf' },
];
const mockInsurers = [
  { id: 1, name: 'Porto Seguro' },
  { id: 2, name: 'SulAmérica' },
  { id: 3, name: 'Mapfre' },
];

function calculateDays(endDate: string) {
  const nowDate = new Date();
  const end = new Date(endDate);
  return Math.floor((end.getTime() - nowDate.getTime()) / 1000 / 60 / 60 / 24);
}
function fileUrl(fileName: string) {
  return `https://policiesrsventaja.s3-sa-east-1.amazonaws.com/${fileName}`;
}

const ControlPanel: React.FC = () => {
  const [signedin, setSignedin] = useState(false);
  const [policies, setPolicies] = useState(mockPolicies);
  const [queryCurrent, setQueryCurrent] = useState('');
  const [queryCurrentResult, setQueryCurrentResult] = useState<typeof mockPolicies>([]);
  const [query, setQuery] = useState('');
  const [queryResult, setQueryResult] = useState<typeof mockPolicies>([]);
  const [insurers] = useState(mockInsurers);
  const [insertForm, setInsertForm] = useState({ name: '', insurer: '', additionalInfo: '', startDate: '', endDate: '', file: null as File | null });
  const [addingPolicy, setAddingPolicy] = useState(false);
  const [displayAlert, setDisplayAlert] = useState(false);
  const [displaySuccess, setDisplaySuccess] = useState(false);
  const [displayQueryCurrent, setDisplayQueryCurrent] = useState(false);
  const [displayQueryAll, setDisplayQueryAll] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    // Check authentication
    setSignedin(true);
    // setSignedin(!!sessionStorage.getItem('Token'));
  }, []);

  // Tab 1: Due Policies
  const handleRenewalToggle = (id: number) => {
    setPolicies(policies => policies.map(p => p.id === id ? { ...p, calculated: !p.calculated } : p));
  };

  // Tab 2: Search Current Policies
  const handleQueryCurrentSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!queryCurrent) {
      setDisplayQueryCurrent(true);
      return;
    }
    setDisplayQueryCurrent(false);
    setQueryCurrentResult(policies.filter(p => p.customer_name.toLowerCase().includes(queryCurrent.toLowerCase())));
    setQueryCurrent('');
  };

  // Tab 3: Search All Policies
  const handleQuerySubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!query) {
      setDisplayQueryAll(true);
      return;
    }
    setDisplayQueryAll(false);
    setQueryResult(policies.filter(p => p.customer_name.toLowerCase().includes(query.toLowerCase())));
    setQuery('');
  };
  const handleDelete = (id: number) => {
    setQueryResult(q => q.filter(p => p.id !== id));
  };

  // Tab 4: Register Policy
  const handleInsertChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setInsertForm(f => ({ ...f, [name]: value }));
  };
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setInsertForm(f => ({ ...f, file: e.target.files![0] }));
    }
  };
  const handleInsertSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setAddingPolicy(true);
    if (!insertForm.name || !insertForm.insurer || !insertForm.additionalInfo || !insertForm.startDate || !insertForm.endDate || !insertForm.file) {
      setDisplayAlert(true);
      setAddingPolicy(false);
      return;
    }
    setDisplayAlert(false);
    setTimeout(() => {
      setAddingPolicy(false);
      setDisplaySuccess(true);
      setInsertForm({ name: '', insurer: '', additionalInfo: '', startDate: '', endDate: '', file: null });
      if (fileInputRef.current) fileInputRef.current.value = '';
    }, 1000);
  };

  if (!signedin) {
    return (
      <div className="container my-5 text-center">
        <h3>Você precisa estar autenticado para acessar o Painel de Controle.</h3>
      </div>
    );
  }

  return (
    <div className="container-fluid p-0" style={{ minHeight: '100vh', background: '#fff' }}>
      <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <div className="collapse navbar-collapse justify-content-center">
          <ul className="navbar-nav">
            <li className="nav-item"><a className="nav-link" href="/homepage">Página Inicial</a></li>
          </ul>
        </div>
      </nav>
      <div className="d-flex justify-content-center align-items-center position-relative" style={{ height: 220 }}>
        <img alt="RS Ventaja" src={process.env.PUBLIC_URL + '/rsventajaheader.png'} width="200" height="200" style={{ position: 'absolute' }} />
      </div>
      <Tabs defaultActiveKey="due" className="mb-3 container mt-4">
        {/* Tab 1: Due Policies */}
        <Tab eventKey="due" title="Apólices a vencer">
          <div className="title h5 mb-3">Apólices com vencimento nos próximos 30 dias</div>
          <Table striped bordered hover size="sm">
            <thead>
              <tr>
                <th>Calculado?</th>
                <th>Dias Restantes</th>
                <th>Nome</th>
                <th>Seguradora</th>
                <th>Informações Adicionais</th>
                <th>Início</th>
                <th>Vencimento</th>
                <th>Ação</th>
              </tr>
            </thead>
            <tbody>
              {policies.map(p => (
                <tr key={p.id}>
                  <td><Form.Check type="checkbox" checked={p.calculated} onChange={() => handleRenewalToggle(p.id)} /></td>
                  <td>{calculateDays(p.end_date)}</td>
                  <td>{p.customer_name}</td>
                  <td>{p.insurer}</td>
                  <td>{p.detail}</td>
                  <td>{new Date(p.start_date).toLocaleDateString('pt-BR')}</td>
                  <td>{new Date(p.end_date).toLocaleDateString('pt-BR')}</td>
                  <td><a className="btn btn-primary btn-sm" href={fileUrl(p.file_name)} target="_blank" rel="noopener noreferrer">Abrir</a></td>
                </tr>
              ))}
            </tbody>
          </Table>
        </Tab>
        {/* Tab 2: Search Current Policies */}
        <Tab eventKey="current" title="Buscar apólices vigentes">
          {displayQueryCurrent && <Alert variant="warning" onClose={() => setDisplayQueryCurrent(false)} dismissible>Favor preencher o nome para realizar a busca.</Alert>}
          <div className="title h5 mb-3">Buscar apólices vigentes</div>
          <Form onSubmit={handleQueryCurrentSubmit} className="mb-3">
            <Form.Group className="mb-2" style={{ maxWidth: 400 }}>
              <Form.Label>Digite parte ou o nome do cliente</Form.Label>
              <Form.Control type="text" value={queryCurrent} onChange={e => setQueryCurrent(e.target.value)} />
            </Form.Group>
            <Button type="submit" variant="primary">Buscar</Button>
          </Form>
          {queryCurrentResult.length > 0 && (
            <Table striped bordered hover size="sm">
              <thead>
                <tr>
                  <th>Dias Restantes</th>
                  <th>Nome</th>
                  <th>Seguradora</th>
                  <th>Informações Adicionais</th>
                  <th>Início</th>
                  <th>Vencimento</th>
                  <th>Ação</th>
                </tr>
              </thead>
              <tbody>
                {queryCurrentResult.map(p => (
                  <tr key={p.id}>
                    <td>{calculateDays(p.end_date)}</td>
                    <td>{p.customer_name}</td>
                    <td>{p.insurer}</td>
                    <td>{p.detail}</td>
                    <td>{new Date(p.start_date).toLocaleDateString('pt-BR')}</td>
                    <td>{new Date(p.end_date).toLocaleDateString('pt-BR')}</td>
                    <td><a className="btn btn-primary btn-sm" href={fileUrl(p.file_name)} target="_blank" rel="noopener noreferrer">Abrir</a></td>
                  </tr>
                ))}
              </tbody>
            </Table>
          )}
        </Tab>
        {/* Tab 3: Search All Policies */}
        <Tab eventKey="all" title="Buscar apólices">
          {displayQueryAll && <Alert variant="warning" onClose={() => setDisplayQueryAll(false)} dismissible>Favor preencher o nome para realizar a busca.</Alert>}
          <div className="title h5 mb-3">Buscar apólices</div>
          <Form onSubmit={handleQuerySubmit} className="mb-3">
            <Form.Group className="mb-2" style={{ maxWidth: 400 }}>
              <Form.Label>Digite parte ou o nome do cliente</Form.Label>
              <Form.Control type="text" value={query} onChange={e => setQuery(e.target.value)} />
            </Form.Group>
            <Button type="submit" variant="primary">Buscar</Button>
          </Form>
          {queryResult.length > 0 && (
            <Table striped bordered hover size="sm">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Seguradora</th>
                  <th>Informações Adicionais</th>
                  <th>Início</th>
                  <th>Vencimento</th>
                  <th>Abrir</th>
                  <th>Excluir</th>
                </tr>
              </thead>
              <tbody>
                {queryResult.map(p => (
                  <tr key={p.id}>
                    <td>{p.customer_name}</td>
                    <td>{p.insurer}</td>
                    <td>{p.detail}</td>
                    <td>{new Date(p.start_date).toLocaleDateString('pt-BR')}</td>
                    <td>{new Date(p.end_date).toLocaleDateString('pt-BR')}</td>
                    <td><a className="btn btn-primary btn-sm" href={fileUrl(p.file_name)} target="_blank" rel="noopener noreferrer">Abrir</a></td>
                    <td><Button variant="danger" size="sm" onClick={() => handleDelete(p.id)}>Excluir</Button></td>
                  </tr>
                ))}
              </tbody>
            </Table>
          )}
        </Tab>
        {/* Tab 4: Register Policy */}
        <Tab eventKey="register" title="Cadastrar apólice">
          {displayAlert && <Alert variant="warning" onClose={() => setDisplayAlert(false)} dismissible>Favor preencher todos os campos antes de prosseguir!</Alert>}
          {displaySuccess && <Alert variant="success" onClose={() => setDisplaySuccess(false)} dismissible>Cadastro realizado com sucesso!</Alert>}
          <div className="title h5 mb-3">Cadastrar apólice</div>
          {addingPolicy && <div className="text-center my-3"><Spinner animation="border" variant="primary" /></div>}
          <Form onSubmit={handleInsertSubmit} className="mb-3">
            <Form.Group className="mb-2">
              <Form.Label>Nome do proponente</Form.Label>
              <Form.Control type="text" name="name" value={insertForm.name} onChange={handleInsertChange} />
            </Form.Group>
            <Form.Group className="mb-2">
              <Form.Label>Seguradora</Form.Label>
              <Form.Select name="insurer" value={insertForm.insurer} onChange={handleInsertChange}>
                <option value="">Selecione</option>
                {insurers.map(ins => <option key={ins.id} value={ins.name}>{ins.name}</option>)}
              </Form.Select>
            </Form.Group>
            <Form.Group className="mb-2">
              <Form.Label>Informações adicionais</Form.Label>
              <Form.Control type="text" name="additionalInfo" maxLength={50} value={insertForm.additionalInfo} onChange={handleInsertChange} />
            </Form.Group>
            <Form.Group className="mb-2">
              <Form.Label>Data de início de vigência</Form.Label>
              <Form.Control type="date" name="startDate" value={insertForm.startDate} onChange={handleInsertChange} />
            </Form.Group>
            <Form.Group className="mb-2">
              <Form.Label>Data de fim de vigência</Form.Label>
              <Form.Control type="date" name="endDate" value={insertForm.endDate} onChange={handleInsertChange} />
            </Form.Group>
            <Form.Group className="mb-2">
              <Form.Label>Arquivo PDF</Form.Label>
              <Form.Control type="file" accept="application/pdf" ref={fileInputRef} onChange={handleFileChange} />
            </Form.Group>
            <Button type="submit" variant="primary" className="w-100" disabled={addingPolicy}>Cadastrar</Button>
          </Form>
        </Tab>
      </Tabs>
    </div>
  );
};

export default ControlPanel;
