// rsventajaweb-react/src/App.tsx
import React from 'react';
import { BrowserRouter as Router, Route, Routes, Navigate, Link } from 'react-router-dom';
import 'bootstrap/dist/css/bootstrap.min.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faEnvelope, faCar, faHome, faArrowUp, faHeartbeat, faBuilding, faBriefcase, faMobileAlt, faPencilAlt } from '@fortawesome/free-solid-svg-icons';
import Login from './Login';
import ControlPanel from './ControlPanel';

function Homepage() {
  return (
    <div className="container-fluid p-0" style={{ minHeight: '100vh', background: '#fff' }}>
      {/* Navbar */}
      <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <div className="collapse navbar-collapse justify-content-center">
          <ul className="navbar-nav">
            <li className="nav-item"><a className="nav-link" href="#sobre">Quem somos</a></li>
            <li className="nav-item"><a className="nav-link" href="#produtos">Produtos</a></li>
            <li className="nav-item"><a className="nav-link" href="#seguradoras">Seguradoras</a></li>
            <li className="nav-item"><a className="nav-link" href="#contato">Contato</a></li>
            <li className="nav-item"><Link className="nav-link" to="/login">Painel de Controle</Link></li>
          </ul>
        </div>
      </nav>
      {/* Header */}
      <div className="d-flex justify-content-center align-items-center position-relative" style={{ height: 220 }}>
        <img alt="RS Ventaja" className="logobig" src={process.env.PUBLIC_URL + '/rsventajaheader.png'} width="200" height="200" style={{ position: 'absolute' }} />
      </div>
      {/* Main Content */}
      <main className="d-flex flex-column align-items-center">
        {/* Quem somos */}
        <section id="sobre" className="my-5 w-100 d-flex flex-column align-items-center">
          <div className="title h3 mb-3">Quem somos</div>
          <div className="abouttext text-center" style={{ maxWidth: 600 }}>
            No mercado há 20 anos, trabalhamos com atenção especial às necessidades individuais do cliente. Temos orgulho em
            construir relações de confiança, possuindo clientes satisfeitos pelo nosso atendimento personalizado e bem
            amparados pelas coberturas que oferecemos.
          </div>
        </section>
        {/* Produtos */}
        <section id="produtos" className="my-5 w-100 d-flex flex-column align-items-center">
          <div className="title h3 mb-4">Produtos</div>
          <div className="row w-100 justify-content-center">
            <div className="col-md-2 col-12 mb-4 d-flex flex-column align-items-center">
              <div className="subtitle h5">Seguro de Automóvel</div>
              <FontAwesomeIcon icon={faCar} size="3x" className="mb-2" />
              <p className="subtitledesc">Cobertura e assistência 24h</p>
              <a href="https://wwws.portoseguro.com.br/vendaonline/automovel/home.ns?cod=3f559c36a4824742a4b2ce6c6ca42463&utm_source=43254J&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_AIQ7YJ&utm_content=RS_VENTAJA_CORRETORA_DE_SEGUROS_LTDA&origem=Site" target="_blank" rel="noopener noreferrer">
                <button className="btn btn-primary">Faça uma cotação</button>
              </a>
            </div>
            <div className="col-md-2 col-12 mb-4 d-flex flex-column align-items-center">
              <div className="subtitle h5">Seguro Residencial</div>
              <FontAwesomeIcon icon={faHome} size="3x" className="mb-2" />
              <p className="subtitledesc">...também para sua casa!</p>
              <a href="https://wwws.portoseguro.com.br/vendaonline/residencia/home.ns?cod=b316cc04aab441c2b853e91f7c31b6fe&utm_source=43254J&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_AIQ7YJ&utm_content=RS_VENTAJA_CORRETORA_DE_SEGUROS_LTDA&origem=Site" target="_blank" rel="noopener noreferrer">
                <button className="btn btn-primary">Faça uma cotação</button>
              </a>
            </div>
            <div className="col-md-2 col-12 mb-4 d-flex flex-column align-items-center">
              <div className="subtitle h5">Seguro Empresarial</div>
              <FontAwesomeIcon icon={faBuilding} size="3x" className="mb-2" />
              <p className="subtitledesc">...e sua empresa!</p>
              <a href="#contato">
                <button className="btn btn-primary">Faça uma cotação</button>
              </a>
            </div>
            <div className="col-md-2 col-12 mb-4 d-flex flex-column align-items-center">
              <div className="subtitle h5">Responsabilidade Civil</div>
              <FontAwesomeIcon icon={faBriefcase} size="3x" className="mb-2" />
              <p className="subtitledesc">Pra quando tudo dá errado</p>
              <a href="#contato">
                <button className="btn btn-primary">Faça uma cotação</button>
              </a>
            </div>
            <div className="col-md-2 col-12 mb-4 d-flex flex-column align-items-center">
              <div className="subtitle h5">Seguro de Vida</div>
              <FontAwesomeIcon icon={faHeartbeat} size="3x" className="mb-2" />
              <p className="subtitledesc">Preocupação com a sua família</p>
              <a href="https://wwws.portoseguro.com.br/vendaonline/vidamaissimples/home.ns?cod=f4c49db5b36c4ad0a84c46770bdf1454&utm_source=43254J&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_AIQ7YJ&utm_content=RS_VENTAJA_CORRETORA_DE_SEGUROS_LTDA&origem=Site" target="_blank" rel="noopener noreferrer">
                <button className="btn btn-primary">Faça uma cotação</button>
              </a>
            </div>
            <div className="col-md-2 col-12 mb-4 d-flex flex-column align-items-center">
              <div className="subtitle h5">Riscos Diversos</div>
              <FontAwesomeIcon icon={faMobileAlt} size="3x" className="mb-2" />
              <p className="subtitledesc">Seus equipamentos protegidos</p>
              <a href="https://wwws.portoseguro.com.br/vendaonline/equipamentosportateis/home.ns?cod=0ba8daaf22d945eea030713c4ce34678&utm_source=43254J&utm_medium=geradorLinks&utm_campaign=GeradordeLinks_AIQ7YJ&utm_content=RS_VENTAJA_CORRETORA_DE_SEGUROS_LTDA&origem=Site" target="_blank" rel="noopener noreferrer">
                <button className="btn btn-primary">Faça uma cotação</button>
              </a>
            </div>
          </div>
        </section>
        {/* Seguradoras */}
        <section id="seguradoras" className="my-5 w-100 d-flex flex-column align-items-center">
          <div className="title h3 mb-4">Seguradoras</div>
          <div className="row w-100 justify-content-center">
            {[
              { name: 'Porto Seguro', img: 'porto.jpg', url: 'https://www.portoseguro.com.br/' },
              { name: 'Unimed', img: 'unimed.jpg', url: 'https://www.segurosunimed.com.br/' },
              { name: 'Mapfre', img: 'mapfre.png', url: 'https://www.mapfre.com.br/' },
              { name: 'Azul', img: 'azul.jpg', url: 'https://www.azulseguros.com.br/' },
              { name: 'HDI', img: 'hdi.jpg', url: 'https://www.hdiseguros.com.br/' },
              { name: 'SulAmérica', img: 'sulamerica.png', url: 'https://portal.sulamericaseguros.com.br/' },
              { name: 'Itaú', img: 'itau.png', url: 'https://www.itau.com.br/seguros/' },
              { name: 'Tokio Marine', img: 'tokiomarine.png', url: 'https://www.tokiomarine.com.br/' },
              { name: 'Sompo', img: 'sompo.png', url: 'https://sompo.com.br/' },
            ].map((insurer, idx) => (
              <div key={insurer.name} className="col-md-2 col-4 mb-4 d-flex flex-column align-items-center">
                <a href={insurer.url} target="_blank" rel="noopener noreferrer">
                  <img alt={insurer.name} src={process.env.PUBLIC_URL + '/' + insurer.img} className="img-circle mb-2" width="60" height="60" />
                </a>
                <p>{insurer.name}</p>
              </div>
            ))}
          </div>
        </section>
        {/* Contato */}
        <section id="contato" className="my-5 w-100 d-flex flex-column align-items-center">
          <div className="title h3 mb-3">Contato</div>
          <div className="d-flex flex-column align-items-center">
            <p>Roberto Ventaja</p>
            <p style={{ color: 'grey' }}>Corretor de Seguros</p>
            <p>roberto@rsventaja.com <a href="mailto:roberto@rsventaja.com"><FontAwesomeIcon icon={faEnvelope} style={{ color: 'grey' }} /></a></p>
          </div>
          <a href="#" title="To Top">
            <FontAwesomeIcon icon={faArrowUp} size="2x" style={{ color: 'grey' }} />
          </a>
        </section>
      </main>
    </div>
  );
}

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/homepage" element={<Homepage />} />
        <Route path="/login" element={<Login />} />
        <Route path="/controlpanel" element={<ControlPanel />} />
        <Route path="/" element={<Navigate to="/homepage" replace />} />
      </Routes>
    </Router>
  );
}

export default App;

// rsventajaweb/src/app/app.component.ts
import { Component } from '@angular/core';
import {  faEnvelope, faCar , faHome, faArrowUp, faHeartbeat, faBuilding, faBriefcase, faMobileAlt } from '@fortawesome/free-solid-svg-icons';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'rsventajaweb';
  faCar = faCar;
  faHome = faHome;
  faHeartbeat = faHeartbeat;
  faBuilding = faBuilding;
  faBriefcase = faBriefcase;
  faMobileAlt = faMobileAlt;
  isNavbarCollapsed = false;
  faArrowUp = faArrowUp;
  faEnvelope = faEnvelope;
}

<div>
  <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="#">
      <img width="40" alt="RS Ventaja" src="../assets/rsventajalogo.png" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#sobre">Sobre nós</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#produtos">Produtos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#seguradoras">Seguradoras</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contato">Contato</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="jumbotron text-center">
    <img alt="RS Ventaja" src="../assets/rsventajalogo.png" width="100" height="100">

    <h1><b>RS Ventaja</b></h1>
    <h4>Corretora de Seguros</h4>

  </div>
  <div class="content" role="main">

    <div id="sobre" class="container-fluid">
      <div class="row col-sm-8">
        <h2>Sobre nós</h2><br>
        <h5>No mercado há 16 anos, trabalhamos com atenção especial às necessidades individuais do cliente.</h5><br>
        <p>Temos orgulho em construir relações de confiança, possuindo clientes satisfeitos pelo nosso atendimento
          personalizado e bem amparados pelas coberturas que oferecemos.</p>
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>
    </div>
    <div id="produtos" class="container-fluid text-center">
      <h2>Produtos</h2>
      <h4>Trabalhamos com os seguintes seguros:</h4>
      <br>
      <div class="row slideanim">
        <div class="col-sm-4">
          <fa-icon class="fa-7x" [icon]="faCar"
            ngbTooltip="É o seguro para carros, caminhões, motocicletas e outros veículos rodoviários. Seu principal uso é fornecer proteção financeira contra danos físicos ou lesões corporais resultantes de colisões no trânsito e contra a responsabilidade que também pode resultar de incidentes em um veículo.">
          </fa-icon>
          <h4>Automóvel</h4>
          <p>Cobertura contra roubos, acidentes, e com assistência 24h!</p>
        </div>
        <div class="col-sm-4">
          <fa-icon class="fa-7x" [icon]="faHome"
            ngbTooltip="Protege a estrutura da casa e o que está dentro do imóvel. Oferece ainda serviços de manutenção e reparos.">
          </fa-icon>
          <h4>Residencial</h4>
          <p>...também para sua casa!</p>
        </div>
        <div class="col-sm-4">
          <fa-icon class="fa-7x" [icon]="faBuilding"
            ngbTooltip="Oferece diversas coberturas para funcionários, finanças e patrimônio do seu negócio."></fa-icon>
          <h4>Empresarial</h4>
          <p>...e sua empresa!</p>
        </div>
      </div>
      <br><br>
      <div class="row slideanim">
        <div class="col-sm-4">
          <fa-icon class="fa-7x" [icon]="faBriefcase"
            ngbTooltip="Cobre indenizações por danos realizados contra outrem, pelo segurado ou por terceiros tutelados ou sob sua responsabilidade.">
          </fa-icon>
          <h4>Responsabilidade Civil</h4>
          <p>Quando tudo dá errado, a indenização é por nossa conta!</p>
        </div>
        <div class="col-sm-4">
          <fa-icon class="fa-7x" [icon]="faHeartbeat"
            ngbTooltip="O seguro de vida é um contrato entre o titular da apólice de seguro e uma seguradora ou seguradora, em que a seguradora promete pagar a um beneficiário designado uma quantia em dinheiro em troca de um prêmio, com a morte de uma pessoa segurada.">
          </fa-icon>
          <h4>Vida</h4>
          <p>Preocupação com a sua família!</p>
        </div>
        <div class="col-sm-4">
          <fa-icon class="fa-7x" [icon]="faMobileAlt"
            ngbTooltip="O ramo de Riscos Diversos visa atender necessidades específicas de cobertura não encontradas nos ramos tradicionais de seguros. Desse modo, oferece várias modalidades e diversas coberturas para os riscos de perdas e danos materiais decorrentes de causa externa, exceto aqueles expressamente excluídos.">
          </fa-icon>
          <h4>Riscos Diversos</h4>
          <p>Seus equipamentos protegidos!</p>
        </div>
      </div>
    </div>

    <div id="seguradoras" class="container-fluid text-center bg-grey">
      <h3>Seguradoras Parceiras</h3><br><br>
      <div class="row slideanim">
        <div class="col-sm-4">
          <a href="https://www.portoseguro.com.br/" target="_blank">
            <img alt="Porto Seguro" src="../assets/porto.jpg" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>Porto Seguro</h5>
        </div>
        <div class="col-sm-4">
          <a href="https://www.segurosunimed.com.br/" target="_blank">
            <img alt="Unimed" src="../assets/unimed.jpg" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>Unimed</h5>
        </div>
        <div class="col-sm-4">
          <a href="https://www.mapfre.com.br/" target="_blank">
            <img alt="Mapfre" src="../assets/mapfre.png" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>Mapfre</h5>
        </div>
      </div>
      <br>

      <div class="row slideanim">
        <div class="col-sm-4">
          <a href="https://www.azulseguros.com.br/" target="_blank">
            <img alt="Azul" src="../assets/azul.jpg" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>Azul</h5>
        </div>
        <div class="col-sm-4">
          <a href="https://www.hdiseguros.com.br/" target="_blank">
            <img alt="HDI" src="../assets/hdi.jpg" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>HDI</h5>
        </div>
        <div class="col-sm-4">
          <a href="https://portal.sulamericaseguros.com.br/" target="_blank">
            <img alt="SulAmérica" src="../assets/sulamerica.png" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>SulAmérica</h5>
        </div>
      </div>
      <br>
      <div class="row slideanim">
        <div class="col-sm-4">
          <a href="https://www.itau.com.br/seguros/" target="_blank">
            <img alt="Itaú" src="../assets/itau.png" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>Itaú</h5>
        </div>
        <div class="col-sm-4">
          <a href="https://www.tokiomarine.com.br/" target="_blank">
            <img alt="Tokio Marine" src="../assets/tokiomarine.png" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>Tokio Marine</h5>
        </div>
        <div class="col-sm-4">
          <a href="https://sompo.com.br/" target="_blank">
            <img alt="Sompo" src="../assets/sompo.png" class="img-circle" width="60" height="60">
          </a>
          <br>
          <h5>Sompo</h5>
        </div>
      </div>
      <br>
      <br>
      <br>

    </div>

    <div id="contato" class="container-fluid text-center bg-grey">
      <h2>Contato</h2>
      <br>
      <h4><b>Roberto Ventaja</b></h4>
      <h5 style="color:grey">Corretor de Seguros</h5>
      <h6>roberto@rsventaja.com <a href="mailto:roberto@rsventaja.com">
          <fa-icon style="color:grey" [icon]="faEnvelope"></fa-icon>
        </a></h6>
        <br>
        <br>
        <br>  
    </div>
    <a href="#home" title="To Top">
      <fa-icon class="fa-2x red" style="color:grey" [icon]="faArrowUp"></fa-icon>
    </a>
  </div>
</div>
